spring:
  datasource:
    url: jdbc:mysql://localhost:3307/restaurants_management
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

    servlet:
      multipart:
        max-file-size: 10MB

jwt:
  privateKey: ${JWT_PRIVATE_KEY}

fileUpLoad:
  rootPath: ${UPLOAD_ROOT_PATH}